name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest # Changed to Windows for System.Media.SoundPlayer support

    steps:
    - uses: actions/checkout@v4 # Updated to latest checkout version
      name: Checkout code

    - name: Setup .NET
      uses: actions/setup-dotnet@v4 # Updated to latest setup-dotnet version
      with:
        dotnet-version: '6.0.x' # Kept .NET 6.0; consider '8.0.x' for latest LTS

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    # Optional: Comment out or remove if no test project exists
    - name: Test
      run: dotnet test --no-build --verbosity normal
      # If no tests exist, add a condition to skip or add a placeholder
      continue-on-error: true # Allows workflow to continue if test step fails (e.g., no tests)
